# Get base SDK Image from Microsoft
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Copy the CSPROJ file and restore any dependencies (NUGET)
COPY *.csproj ./
RUN dotnet restore

# Copy the project files and build the release
COPY . ./
RUN dotnet publish -c Release -o out

#Generate runtime image

FROM mcr.microsoft.com/dotnet/aspnet:7.0
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "CustomerService.dll" ]